import = [ "~/dotfiles/alacritty/gruvbox_material_medium_dark.toml" ]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding = { x = 25, y = 10 }
opacity = 1
dynamic_padding = false
dimensions = { columns = 120, lines = 30 }

[font]
size = 16.0
offset = { x = 1, y = 1 }

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[cursor]
style = { shape= "Block", blinking= "Off"}

[scrolling]
history = 10000

[keyboard]
bindings = [{ key= "u",   mods = "Command", action= "ToggleSimpleFullscreen" }]
