import = [ "~/dotfiles/alacritty/colors/gruvbox.toml" ]
live_config_reload = true

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
# padding = { x = 10, y = 30 }
padding = { x = 10, y = 20 }
opacity = 1
dynamic_padding = true
dimensions = { columns = 120, lines = 30 }

[font]
size = 16.0
offset = { x = 1, y = 1 }

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[cursor]
style = { shape= "Block", blinking= "Off"}

[scrolling]
history = 10000

[keyboard]
bindings = [{ key= "u",   mods = "Command", action= "ToggleSimpleFullscreen" }]
