#!usr/bin/env bash

# https://morgan.cugerone.com/blog/workarounds-to-git-worktree-using-bare-repository-and-cannot-fetch-remote-branches/

set -e

# git-clone-bare git@github.com:name/repo.git
# => clones to /repo.git
#
# git-clone-bare git@github.com:name/repo.git my-repo
# => clones to /my-repo

url=$1
basename=${url##*/}
name=${2:-${basename%.*}}

mkdir $name
cd "$name"

git clone --bare "$url" .bare
echo "gitdir: ./.bare" >.git

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"

git fetch origin
